### ISSUE TITLE
Unsatisfied Recommendations ?

### ISSUE THREAD

**Issue by GunMan-fr** [OSSystems/meta-gstreamer1.0#1]
Dear Sir,

Thanks very much for your work on these recipes.

I try to use them in order to create an Angstrom image with gstreamer1.0 (the standard Angstrom has  gstreamer 0.1). 

To do so, I've setup an oe-core environnement, cloned this repository in oe-core/stuff, I've added the meta-gstreamer1.0 path to the build/conf/bblayers.conf, and I've added to the build/conf/local.conf the line IMAGE_INSTALL_append = " " with all gstreamer package names.

My problem is that a huge lot of plugins are NOT built. Only gst_libav plugins are correctly built. The other plugins stay uninstalled on the final image. When trying to install the generated .ipk, it says for each plugin "unsatisfied recommendation ...." #package-name-here.

I'm a bit confused because the README here explains how dependencies are handled. The particular plugin I'm looking for, uvch264, is NOT built. 

Thanks for your help !

**Comment by otavio** [comment]
I think this can be closed as the source has change quite a lot and this is not more meaningful at current code state.

**Comment by GunMan-fr** [comment]
I think I solved the problem by including all the "-meta" packages. This may not be an issue anymore but at least it was not documented by the time.
