### ISSUE TITLE
alsasink plugin absent

### ISSUE THREAD

**Issue by Madan1993** [OSSystems/meta-gstreamer1.0#10]
hi,
i am not able get alsasink support, same sources was used. following are log:

gst-inspect-1.0 alsasink
No such element or plugin 'alsasink'

i am able to play file but failed to get audio

**Comment by dawagner** [comment]
You may need to explicitly install the gstreamer1.0-plugins-good-alsa package to your image.

**Comment by Madan1993** [comment]
thanks David,

there is any document or source link to proceeds [yocto compatible].

**Comment by dawagner** [comment]
I'm no yocto expert but for instance, you may want to have your own package "rdepend" on gstreamer1.0-plugins-good-alsa. http://www.yoctoproject.org/docs/2.2/mega-manual/mega-manual.html#var-RDEPENDS

**Comment by karora123** [comment]
You need to extended rdepdency of target image to "gstreamer1.0-plugins-good-alsa" and provide path of bitbake recipe of alsa package.
explore the link shared above

**Comment by dv1** [comment]
This seems to be solved. Closing it. If there are still problems, feel free to reopen it.
