### ISSUE TITLE
gstreamer1.0-plugins-bad-opencv build fails on arm neon

### ISSUE THREAD

**Issue by nefethael** [OSSystems/meta-gstreamer1.0#11]
Hi, 

do_configure task of gstreamer1.0-plugins-bad-opencv fails with this error:
gstreamer1.0-plugins-bad/1.12.0-r0/recipe-sysroot/usr/include/opencv2/core/cvdef.h:316:5: error: '__fp16' does not name a type
     __fp16 h;

I'm using 1.12.0 gstreamer version from this layer, with opencv 3.2 from meta-openembedded.

OpenCV 3.2 adds an extra flag -mfpu=neon-fp16 (see https://github.com/openembedded/meta-openembedded/commit/c931bc6a7a2d25432fc10b7cdef3cf5ad922f6d5) and gstreamer does not.

I'm not sure how to resolve this problem, any help fixing this ?

Thanks,
Vincent

**Comment by nefethael** [comment]
Looks like it needs -mfp16-format=ieee somewhere, maybe in configure.ac?

**Comment by dv1** [comment]
Can you retry with 1.14.0 ? I cannot reproduce the problem.

**Comment by nefethael** [comment]
It seems Gstreamer 1.14.0 with Opencv 3.3 doesn't have this issue.

For the record I added in gstreamer1.0-plugins-bad_%.bbappend
TARGET_CFLAGS_append_mx6 = " -mfp16-format=ieee "
