### ISSUE TITLE
gstreamer1.0-plugins-good - lame

### ISSUE THREAD

**Issue by nefethael** [OSSystems/meta-gstreamer1.0#16]
In 1.14.0 Gstreamer version, lame plugin moved to "good", and gstreamer1.0-plugins-good.inc file add lame by default in PACKAGECONFIG:

```
PACKAGECONFIG ??= " \
    ${GSTREAMER_ORC} \
    ${@bb.utils.filter('DISTRO_FEATURES', 'pulseaudio x11', d)} \
    cairo flac gdk-pixbuf gudev jpeg lame libpng mpg123 soup \
    speex taglib v4l2 \
"
PACKAGECONFIG[lame]       = "--enable-lame,--disable-lame,lame"
```

But lame recipe in oe-core (lame_3.99.5.bb) has commercial flag, so it fails to generate "good" package without commercial flag set in whitelist.

**Comment by dv1** [comment]
Good point, thanks. I'll fix this.

**Comment by nefethael** [comment]
@dv1: btw, it's same for mpg123 plugin

**Comment by dv1** [comment]
I committed changes to remove mpg123 and lame until oe-core removed their commercial flags. (mp3 patents expired, and no more licenses are required for mp3, so that flag is not really necessary anymore for these recipes.)
