### ISSUE TITLE
How can I build the gstwebrtc plugins from gst-plugins-bad v1.14

### ISSUE THREAD

**Issue by RobGries** [OSSystems/meta-gstreamer1.0#17]
I'm having some trouble including the gstwebrtc plugins from gst-plugins-bad on v1.14 using the meta-gstreamer1.0 meta layer. 

I think that I am missing some dependencies from my yocto distribution. So far I have libnice json-glib libsoup-2.4 satisfied but for some reason the plugin refuses to build alongside of the other working gstreamer1.0-plugins-bad plugins.

Can anyone provide a list of necessary recipes that will enable webrtc on my build?

**Comment by RobGries** [comment]
So it appears that I'm actually building the plugin without error. However, when using the newly installed plugins it appears that the libgstwebrtc-1.0.so is now being blacklisted for some reason. 

I still think that I'm missing a dependency somewhere, just not quite sure where.

```
gst-inspect-1.0 libgstwebrtc-1.0.so
Plugin Details:
  Name                     libgstwebrtc-1.0.so
  Description              Plugin for blacklisted file
  Filename                 /usr/lib64/gstreamer-1.0/libgstwebrtc-1.0.so
  Version                  0.0.0
  License                  BLACKLIST
  Source module            BLACKLIST
  Binary package           BLACKLIST
  Origin URL               BLACKLIST


  0 features:

```

**Comment by RobGries** [comment]
I figured it out, my yocto environment had an outdated version of libnice in it's recipes. I updated my version of libnice to the latest version, and I am now able to use libgstwebrtc properly.

**Comment by otavio** [comment]
@RobGries glad you fixed it. I am therefore closing this issue.
