### ISSUE TITLE
Error building for Webkit

### ISSUE THREAD

**Issue by gil0109** [OSSystems/meta-gstreamer1.0#20]
I am trying to use the newer gstreamer with webkit.  During build, I received this error:

Error:
 Problem 1: conflicting requests
  - nothing provides gstreamer1.0-plugins-bad-opengl needed by wpewebkit-2.20.1-r0.cortexa7t2hf_neon_vfpv4
 Problem 2: package cog-20180703-r0.cortexa7hf_neon_vfpv4 requires libWPEWebKit-0.1.so.0, but none of the providers can be installed
  - conflicting requests
  - nothing provides gstreamer1.0-plugins-bad-opengl needed by wpewebkit-2.20.1-r0.cortexa7t2hf_neon_vfpv4

**Comment by dv1** [comment]
The OpenGL plugin was moved to -base in 1.14. So you need gstreamer1.0-plugins-base-opengl .

**Comment by gil0109** [comment]
Does that mean I add that the -base to my layer.conf or do I need to replace it in the Webkit layer?  I am new to this and thank you for your help.

**Comment by otavio** [comment]
This needs to be reworked on the downstream layer or your application layer.
