### ISSUE TITLE
Sumo branch?

### ISSUE THREAD

**Issue by philn** [OSSystems/meta-gstreamer1.0#21]
It would be great to have a sumo branch. Thanks!

**Comment by otavio** [comment]
Is it possible for you to confirm if current master works fine on it?

**Comment by philn** [comment]
I have a layer enabling downstream GStreamer patches but those are not build fixes. So I think it's safe to say the build for sumo succeeds, at least for an i-MX6 QuadPlus target.

**Comment by otavio** [comment]
I just made the branch. Please give it a go!
