### ISSUE TITLE
Possible: Gstreamer 1.14 to morty?

### ISSUE THREAD

**Issue by andcor** [OSSystems/meta-gstreamer1.0#24]
Hi
I have a target that I currently only have a yocto morty build system for with a relatively old kernel (3.14), but when looking at the gstreamer release notes there are parts of the changes that might solve some of the problems we are facing. However, the morty branch on this repository is left at 1.12.

My question is therefore; what is the reason for leaving the morty branch at 1.12? Has morty been judged to be too old or would it simply be too much work?
This should not be seen as a feature request but more a request for knowledge so that I better can figure out if I should dive in to make a pull-request for updating the version myself.

Kind regards

Andreas

**Comment by otavio** [comment]
Hello @andcor, thank you for getting in touch.

I understand your need and I'd prefer to not mess up with such old version. The main reasons for that are:

1. risk of breaking existing users
2. motivation to upgrade to new branches
3. effort

The risk is the most important reason; I believe newer branches might work on top of OE-Core at Morty branch but it has it own risks and challenges.

**Comment by dv1** [comment]
I agree. In particular, older oe-core versions have older GLib versions, which might no longer work with GStreamer 1.14. And backporting GLib is a can of worms that should no be opened unless it is absolutely necessary.

**Comment by andcor** [comment]
Thank you. That it valuable inputs. We will then most likely nok try updating gstreamer without also trying to update the version of yocto first.
