### ISSUE TITLE
Last commit : Rename distro_features_check to features_check break Yocto Zeus build

### ISSUE THREAD

**Issue by aurelihein** [OSSystems/meta-gstreamer1.0#29]
Hello,
I understand that the master branch is following latest commit from `meta-openembedded` even if is `master-next` branch, but unfortunately this commit `b5f510e48080b6dc710ff4800feb90ef679c5456` break builds with all `zeus` branches even from `meta-openembedded` `zeus` branch
Is it possible to create a zeus branch that could be maintained starting from commit `bf562ab7bb4dd68e486c71be6ebcf9d872f63b33` ?
Thank you for your feedback

**Comment by otavio** [comment]
We have the branches now; please check if it is Ok for you.
