### ISSUE TITLE
backport 1.4+ support to Dora?

### ISSUE THREAD

**Issue by waTeim** [OSSystems/meta-gstreamer1.0#3]
Is this even possible, or is there some limitation in the os that prevents this?  If it is possible, I have a need to have at least version 1.4 of gstreamer compiled for a dora-based system.  Simply using master fails with the following error message.

```
ERROR: ParseError at /home/jeffw/src/poky/meta-gstreamer1.0/recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad.inc:12: Could not inherit file classes/bluetooth.bbclass
```

The version "git" is supported on all branches, that that might be a workaround, but an actual release would be preferred.

**Comment by dv1** [comment]
Perhaps it is, though the minimum required GLib version may pose a problem. However, I currently have no plans on dora support due to time constraints.

**Comment by dv1** [comment]
Closing this, since dora is quite old by now. Contributions for dora specific updates are welcome!
