### ISSUE TITLE
add support for gatesgarth

### ISSUE THREAD

**Issue by quaresmajose** [OSSystems/meta-gstreamer1.0#41]
I have PR for gatesgarth on top of commit:
c3ba8f0a `conf/layer.conf: Set layer compatible only with gatesgarth`

It is possible to create a `gatesgarth` branch at this commit ?

**Comment by otavio** [comment]
Please send it to master; we can make the branch.

**Comment by otavio** [comment]
In fact I created it.

**Comment by quaresmajose** [comment]
> In fact I created it.

Thanks for that
