### ISSUE TITLE
Why on dunfell LTS branch was gstreamer was bumper to 1.18?

### ISSUE THREAD

**Issue by nandra** [OSSystems/meta-gstreamer1.0#53]
Hi,

this is not an issue just general question. Why gstreamer on LTS branch was bumped from 1.16 to 1.18? I need to use 1.16 internally (I added fix to build it on dunfell but I have still failing gstreamer1.0-python) with:

```
| checking for pygobject-3.0 >= 3.8... yes
| checking for libraries required to embed python... no
| configure: error: Python libs not found. Windows requires Python modules to be explicitly linked to libpython.
```

Thanks.

**Comment by quaresmajose** [comment]
The OE-core dunfell branch have gstreamer 1.16.3. There are no need to use this layer if you don't need gstreamer 1.18.
https://git.yoctoproject.org/cgit/cgit.cgi/poky/log/meta/recipes-multimedia/gstreamer?h=dunfell

**Comment by nandra** [comment]
Ok thanks a lot. I think why I used this repo was that for zeus I need 1.16 gstreamer and now I bumped to dunfell and forgot to drop this meta layer. Thanks.
