### ISSUE TITLE
Missing morty support?

### ISSUE THREAD

**Issue by ndechesne** [OSSystems/meta-gstreamer1.0#6]
hi there,

is this layer still maintained? I don't see any update for the last few months. For example
* morty branch is missing
* gst 1.10 (currently in oe-core/master) is missing from this layer

I am planning to start using this layer, and wanted to get a better idea about its current status.

thanks!

**Comment by dv1** [comment]
morty is still supported - I also added 1.12 recipes. However, I don't think I'll add 1.14.
