### ISSUE TITLE
linking buffer of nested source

### ISSUE THREAD

**Issue by karora123** [OSSystems/meta-gstreamer1.0#7]
Hi,
I am writing a gst plugin which is creating another gst plugin (gstSrc). There is already one gstbuffer created in original plugin, i just wanted to map that buffer with another (nested) gstSrc so that data of gstSrc should copied to original plugin buffer.
Is there any way or any other approach is possible?

**Comment by dv1** [comment]
Please post this question in the GStreamer mailing list, as that's the correct place for this kind of question, thanks.
